core:
  data_iface: ens18
  ran_subnet: "172.20.0.0/16"	# set to empty string to get subnet from 'data_iface'

  slice:
    values_file: "deps/5gc/roles/slice/templates/slice-5g-values.yaml"
    helm:
          chart_ref: aether/sd-core
          chart_version: 1.0.0
    slices:
      "1":
        ip:
            access: "192.168.252.6/24"
            core:   "192.168.250.6/24"
        ue_ip_pool: "172.248.0.0/16"