---

# - name: create /opt/cni/bin/ 
#   file: 
#     path: /opt/cni/bin/
#     recurse: yes
#     state: directory
#   become: true

# - name: create /tmp/cni-plugins
#   file: 
#     path: /tmp/cni-plugins
#     state: directory

# - name: fetch and untar cni-plugins
#   unarchive:
#     src: https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz
#     dest: /tmp/cni-plugins
#     remote_src: yes

# - name: copy /tmp/cni-plugins/static to /opt/cni/bin/
#   copy:
#     src: /tmp/cni-plugins/static
#     dest: /opt/cni/bin/
#     remote_src: yes
#   become: true

- name: add cord chart repo
  kubernetes.core.helm_repository:
    name: cord
    repo_url: "https://charts.opencord.org"
  when: inventory_hostname in groups['master_nodes']

- name: add atomix chart repo
  kubernetes.core.helm_repository:
    name: atomix
    repo_url: "https://charts.atomix.io"
  when: inventory_hostname in groups['master_nodes']

- name: add onosproject chart repo
  kubernetes.core.helm_repository:
    name: onosproject
    repo_url: "https://charts.onosproject.org"
  when: inventory_hostname in groups['master_nodes']

- name: add aether chart repo
  kubernetes.core.helm_repository:
    name: aether
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']

- name: add rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher
    repo_url: "http://charts.rancher.io/"
  when: inventory_hostname in groups['master_nodes']

- name: find {{ core.data_iface }}'s subnet for RAN
  shell: ip route | grep {{ core.data_iface }} | awk '/kernel/ {print $1}' | head -1
  register: result
  when: inventory_hostname in groups['master_nodes']
  become: true

# TODO: check if interface subnet is valid
- set_fact:
    ran_subnet: "{{ result.stdout }}"
  when: inventory_hostname in groups['master_nodes']

- name: remove /tmp/aether-5gc-values.yaml
  file:
    path: "/tmp/aether-5gc-values.yaml"
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: copy aether-5gc-values.yaml to /tmp/aether-5gc-values.yaml
  template:
    src: roles/core/templates/aether-5gc-values.yaml
    dest: "/tmp/aether-5gc-values.yaml"
  when: inventory_hostname in groups['master_nodes']

- name: deploy aether 5gc
  kubernetes.core.helm:
    update_repo_cache: true
    name: sd-core
    release_namespace: omec
    create_namespace: true
    chart_ref: aether/sd-core
    values_files:
      - /tmp/aether-5gc-values.yaml
    wait: true
    force: true
  when: inventory_hostname in groups['master_nodes']
