---

- name: delete route for upf to UE
  shell: |
    ip route del {{ item.value.ue_ip_pool }} via {{ item.value.ip.core[:-3] }}
  when: inventory_hostname in groups['master_nodes']
  with_dict: "{{ core.slice.slices }}"
  become: true
  ignore_errors: yes

- name: remove aether slices
  kubernetes.core.helm:
    name: sd-core
    release_namespace: omec-slice-{{ item.key }}
    state: absent
    wait: true
  with_dict: "{{ core.slice.slices }}"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace omec-slice
  shell: |
    "kubectl delete namespace omec-slice-{{ item.key }}"
  with_dict: "{{ core.slice.slices }}"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

