# Copyright 2022-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourcePrefix": "intel.com",
          "resourceName": "intel_sriov_vfio_access",
          "selectors": {
            "pfNames": ["PFDEV#0"],
            "vendors": ["8086"],
            "drivers": ["vfio-pci"]
          }
        },
        {
          "resourcePrefix": "intel.com",
          "resourceName": "intel_sriov_vfio_core",
          "selectors": {
            "pfNames": ["PFDEV#1"],
            "vendors": ["8086"],
            "drivers": ["vfio-pci"]
          }
        }
      ]
    }

